### ISSUE TITLE
Checker crashing when analyzing calls to `annotatedWith`

### ISSUE THREAD

**Issue by jaysonacosta** [jaysonacosta/guice-checker#33]
The checker is crashing when encountering scenarios like the following:

```java
      AnnotatedBindingBuilder<Integer> integerBinding = bind(Integer.class);
      LinkedBindingBuilder<Integer> namedBinding =
          integerBinding.annotatedWith(Names.named("login timeout seconds"));
      namedBinding.toInstance(10);
```

In `visitMethodInvocation` defined `DependencyInjectionTransfer`, `integerBinding` is definitely annotated with `@Bind({"Integer.class"})` but isn't able to be properly retrieved when trying to access it by the time the analysis encounters the `annotatedWith` method invocation node. Due to the fact that the analysis by this point knows that there must be a bound class within the value of the annotation, it attempts to get it at position `0` and the programs throws an `Exception: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0; java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0`.

Possible problems:
- The checker doesn't know that `Names.named()` is pure, however, this was a problem that I came across previously and solved it by defining it in the `Guice.astub` file.
- Some other methods being used are assumed to not be pure by the checker.

Goal:
- Get the analysis to recognize the aforementioned source code as valid Guice bindings and store them in the map.

**Comment by kelloggm** [comment]
@jaysonacosta can you include the full stacktrace here? There are many calls to `get` that could throw this exception in `visitMethodInvocation`, and I think it's important to be certain which is responsible: at lines 37, 68, 69, and 71.

**Comment by jaysonacosta** [comment]
```
      Last visited tree at line 10 column 1:
      public class InstanceBindingsUsingToInstanceMethodsNotChained {
      Exception: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0; java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.util.Objects.checkIndex(Objects.java:385)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at org.checkerframework.checker.dependencyinjection.DependencyInjectionTransfer.lambda$visitMethodInvocation$0(DependencyInjectionTransfer.java:71)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.checkerframework.checker.dependencyinjection.DependencyInjectionTransfer.visitMethodInvocation(DependencyInjectionTransfer.java:61)
        at org.checkerframework.checker.dependencyinjection.DependencyInjectionTransfer.visitMethodInvocation(DependencyInjectionTransfer.java:21)
        at org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:122)
        at org.checkerframework.dataflow.analysis.AbstractAnalysis.callTransferFunction(AbstractAnalysis.java:349)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.callTransferFunction(ForwardAnalysisImpl.java:376)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysisBlock(ForwardAnalysisImpl.java:151)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysis(ForwardAnalysisImpl.java:105)
        at org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:147)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1541)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1441)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1927)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:421)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:533)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:183)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:851)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:66)
        at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:86)
        at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1030)
        at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:560)
        at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:188)
        at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:876)
        at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1408)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1365)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
        at org.checkerframework.framework.test.TypecheckExecutor.compile(TypecheckExecutor.java:116)
        at org.checkerframework.framework.test.TypecheckExecutor.runTest(TypecheckExecutor.java:31)
        at org.checkerframework.framework.test.CheckerFrameworkPerDirectoryTest.run(CheckerFrameworkPerDirectoryTest.java:152)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
```
